// app/pages/user-manwha/[id].vue
<template>
  <div v-if="loading" class="flex items-center justify-center min-h-[60vh]">
    <Icon name="lucide:loader-2" size="48" class="animate-spin text-primary" />
  </div>

  <div
    v-else-if="error"
    class="flex flex-col items-center justify-center min-h-[60vh] text-white/60"
  >
    <Icon name="lucide:alert-circle" size="48" class="mb-4" />
    <p class="text-lg">{{ error }}</p>
    <NuxtLink to="/" class="mt-4 text-primary hover:underline">Go back to home</NuxtLink>
  </div>

  <div v-else-if="manwha" class="pb-8">
    <div
      v-if="manwha.bannerImage"
      class="hidden md:block not-even:w-full h-[400px] bg-cover bg-center relative -mt-8"
      :style="{ backgroundImage: `url(${manwha.bannerImage})` }"
    >
      <div class="absolute inset-0 bg-gradient-to-b from-transparent via-dark/30 to-dark"></div>
    </div>

    <div
      class="flex flex-row gap-4 md:gap-6 relative z-10 max-w-6xl mx-auto"
      :class="{ 'md:-mt-28': manwha.bannerImage }"
    >
      <div class="w-[120px] md:w-[240px] aspect-[2/3] rounded-lg overflow-hidden shadow-lg">
        <img
          v-if="manwha.coverImage"
          :src="manwha.coverImage"
          :alt="manwha.title"
          class="w-full h-full object-cover"
        />
        <div v-else class="w-full h-full bg-white/10 flex items-center justify-center">
          <Icon name="lucide:file-image" size="64" class="text-white/40" />
        </div>
      </div>

      <div class="flex-1 space-y-6">
        <div>
          <h1 class="text-3xl font-bold text-white mb-2">{{ manwha.title }}</h1>
          <div v-if="manwha.synonyms.length > 0" class="group relative inline-block mb-2">
            <button
              class="text-sm text-white/60 hover:text-primary flex items-center gap-1 transition-colors"
            >
              <Icon name="lucide:info" size="16" />
              <span>
                {{ manwha.synonyms.length }} alternative title{{
                  manwha.synonyms.length > 1 ? 's' : ''
                }}
              </span>
            </button>
            <div
              class="absolute left-0 top-full mt-2 w-max max-w-md bg-dark border border-white/20 rounded-lg p-4 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-20 shadow-xl"
            >
              <p class="text-xs text-white/60 mb-2 font-semibold">Alternative Titles:</p>
              <ul class="space-y-1">
                <li v-for="synonym in manwha.synonyms" :key="synonym" class="text-sm text-white/90">
                  {{ synonym }}
                </li>
              </ul>
            </div>
          </div>
          <div v-if="manwha.meanScore" class="flex items-center gap-2 text-white/80">
            <Icon name="lucide:star" size="20" class="text-yellow-400" />
            <span class="text-lg font-semibold">{{ manwha.meanScore / 10 }}/10</span>
          </div>
        </div>

        <div v-if="manwha.genres.length > 0" class="flex flex-wrap gap-2">
          <span
            v-for="genre in manwha.genres"
            :key="genre"
            class="px-3 py-1 bg-primary/20 text-primary rounded-full text-sm"
          >
            {{ genre }}
          </span>
        </div>

        <div v-if="manwha.description" class="text-white/80 hidden md:block">
          <h2 class="text-xl font-semibold text-white mb-2">Description</h2>
          <div v-dompurify-html="manwha.description" class="prose prose-invert max-w-none"></div>
        </div>
      </div>
    </div>

    <!-- Description for mobile -->
    <div class="max-w-6xl mx-auto mt-4 md:hidden">
      <div v-if="manwha.description" class="text-white/80">
        <h2 class="text-xl font-semibold text-white mb-2">Description</h2>
        <div v-dompurify-html="manwha.description" class="prose prose-invert max-w-none"></div>
      </div>
    </div>

    <div class="bg-white/5 rounded-lg p-6 mt-6 max-w-6xl mx-auto">
      <h2 class="text-xl font-semibold text-white mb-6">My Reading Progress</h2>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label for="status" class="block text-sm font-medium mb-2">Status</label>
          <select
            id="status"
            v-model="userManwhaData.status"
            class="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded text-white focus:ring-primary focus:border-white"
          >
            <option v-for="(label, key) in READING_STATUS" :key="key" :value="key">
              {{ label }}
            </option>
          </select>
        </div>

        <div>
          <label for="lastReadChapter" class="block text-sm font-medium mb-2">
            Current Chapter
          </label>
          <input
            id="lastReadChapter"
            v-model.number="userManwhaData.lastReadChapter"
            type="number"
            min="0"
            class="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded text-white focus:ring-primary focus:border-white"
            placeholder="0"
          />
        </div>

        <div class="md:col-span-2">
          <label for="score" class="block text-sm font-medium mb-2">
            Your Score: {{ userManwhaData.score || 0 }}/10
          </label>
          <input
            id="score"
            v-model.number="userManwhaData.score"
            type="range"
            min="0"
            max="10"
            step="0.5"
            class="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer accent-primary"
          />
          <div class="flex justify-between text-xs text-gray-500 mt-1">
            <span>0</span>
            <span>5</span>
            <span>10</span>
          </div>
        </div>

        <div class="md:col-span-2">
          <label for="readingUrl" class="block text-sm font-medium mb-2">
            Reading URL (optional)
          </label>
          <input
            id="readingUrl"
            v-model="userManwhaData.readingUrl"
            type="url"
            class="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded text-white focus:ring-primary focus:border-white"
            placeholder="https://..."
          />
        </div>

        <div>
          <label for="startedAt" class="block text-sm font-medium mb-2">Start Date</label>
          <input
            id="startedAt"
            v-model="userManwhaData.startedAt"
            type="date"
            readonly
            class="w-full px-4 py-2 bg-gray-800 border border-gray-600 rounded text-gray-400 cursor-not-allowed"
          />
        </div>

        <div>
          <label for="lastReadAt" class="block text-sm font-medium mb-2">Last Read Date</label>
          <input
            id="lastReadAt"
            v-model="userManwhaData.lastReadAt"
            type="date"
            readonly
            class="w-full px-4 py-2 bg-gray-800 border border-gray-600 rounded text-gray-400 cursor-not-allowed"
          />
        </div>

        <div class="md:col-span-2 flex items-center gap-3">
          <input
            id="isFavorite"
            v-model="userManwhaData.isFavorite"
            type="checkbox"
            class="w-5 h-5 rounded"
          />
          <label for="isFavorite" class="text-sm font-medium text-white/80 cursor-pointer">
            Mark as Favorite
          </label>
        </div>
      </div>

      <div class="flex gap-3 pt-6 mt-6 border-t border-gray-700">
        <button
          class="flex-1 px-6 py-3 bg-primary hover:bg-primary-lighter rounded text-white font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          :disabled="saving"
          @click="saveUserManwha"
        >
          <span v-if="saving" class="flex items-center justify-center gap-2">
            <Icon name="lucide:loader-2" size="20" class="animate-spin" />
            Saving...
          </span>
          <span v-else>Save</span>
        </button>
        <NuxtLink
          to="/"
          class="px-6 py-3 bg-gray-700 hover:bg-gray-600 rounded text-white font-medium transition-colors flex items-center justify-center"
        >
          Cancel
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { READING_STATUS } from '~~/shared/types/reading-status';

const route = useRoute();
const id = route.params.id as string;

const loading = ref(true);
const saving = ref(false);
const error = ref<string | null>(null);
const manwha = ref<Manwha | null>(null);

const userManwhaData = ref({
  status: 'reading' as ReadingStatus,
  lastReadChapter: 0,
  score: null as number | null,
  readingUrl: null as string | null,
  startedAt: new Date().toISOString().split('T')[0],
  lastReadAt: new Date().toISOString().split('T')[0],
  isFavorite: false,
});

onMounted(async () => {
  try {
    loading.value = true;
    const data = await $fetch('/api/anilist/detail', {
      query: { id },
    });
    manwha.value = data as Manwha;
  } catch (err) {
    console.error('Failed to fetch manwha details:', err);
    error.value = 'Failed to load manwha details. Please try again later.';
  } finally {
    loading.value = false;
  }
});

async function saveUserManwha() {
  saving.value = true;
  try {
    await new Promise(resolve => setTimeout(resolve, 1000));
    navigateTo('/');
  } catch (err) {
    console.error('Failed to save user manwha:', err);
    alert('Failed to save. Please try again.');
  } finally {
    saving.value = false;
  }
}
</script>

<style scoped>
input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  opacity: 1;
}

.prose {
  max-height: 150px;
  overflow-y: auto;
}

* {
  scrollbar-width: auto;
  scrollbar-color: rgba(255, 255, 255, 0.2) transparent;
}
</style>

// src/routes/(authenticated)/manwhas/[id]/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import StatusBadge from "$lib/components/StatusBadge.svelte";
  import ChapterInfo from "$lib/components/ChapterInfo.svelte";
  import IconButton from "$lib/components/IconButton.svelte";
  import { renderIcon } from "$lib/icons";

  interface Props {
    data: PageData;
  }

  let { data }: Props = $props();

  function formatDate(dateValue?: Date | string) {
    if (!dateValue) return "N/A";
    try {
      const date = typeof dateValue === "string"
        ? new Date(dateValue)
        : dateValue;
      return date.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    } catch {
      return "Invalid date";
    }
  }

  function handleCoverClick() {
    if (data.manwha.link) {
      window.open(data.manwha.link, "_blank", "noopener,noreferrer");
    }
  }
</script>

<svelte:head>
  <title>{data.manwha.title} - Manwha Tracker</title>
</svelte:head>

<div class="container">
  <div class="header-section">
    <h1 class="page-title">{data.manwha.title}</h1>
    <div class="header-actions">
      <IconButton
        icon="edit"
        href="/manwhas/{data.manwha._id}/edit"
        title="Edit Manwha"
        ariaLabel="Edit {data.manwha.title}"
        textColor="text-blue-400"
        bgColor="bg-blue-900/20"
        hoverBgColor="hover:bg-blue-900/30"
        size="lg"
      />
    </div>
  </div>

  <div class="content-grid">
    {#if data.manwha.coverImage}
      <div class="cover-section">
        <button
          onclick={handleCoverClick}
          class="cover-button"
          class:clickable={data.manwha.link}
          disabled={!data.manwha.link}
          title={data.manwha.link ? "Visit manwha homepage" : ""}
        >
          <img
            src={data.manwha.coverImage}
            alt="{data.manwha.title} cover"
            class="cover-image"
          />
          {#if data.manwha.link}
            <div class="cover-overlay">
              <div class="overlay-icon">
                {@html renderIcon("externalLink", "w-8 h-8")}
              </div>
              <span class="overlay-text">Visit Homepage</span>
            </div>
          {/if}
        </button>
      </div>
    {/if}

    <div class="info-section">
      <div class="info-card">
        <h2 class="section-title">Details</h2>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Status</span>
            <div class="info-value">
              <StatusBadge status={data.manwha.status} />
            </div>
          </div>

          <div class="info-item">
            <span class="info-label">Current Chapter</span>
            <div class="info-value">
              <ChapterInfo
                chapter={data.manwha.currentChapter}
                link={data.manwha.link}
              />
            </div>
          </div>

          {#if data.manwha.rating}
            <div class="info-item">
              <span class="info-label">Rating</span>
              <span class="info-value rating">{data.manwha.rating}/10</span>
            </div>
          {/if}

          <div class="info-item">
            <span class="info-label">Started</span>
            <span class="info-value">{formatDate(data.manwha.startDate)}</span>
          </div>

          {#if data.manwha.endDate}
            <div class="info-item">
              <span class="info-label">Ended</span>
              <span class="info-value">{formatDate(data.manwha.endDate)}</span>
            </div>
          {/if}

          <div class="info-item">
            <span class="info-label">Last Read</span>
            <span class="info-value">{formatDate(data.manwha.lastReadAt)}</span>
          </div>
        </div>
      </div>

      {#if data.manwha.description}
        <div class="info-card">
          <h2 class="section-title">Description</h2>
          <p class="description-text">{data.manwha.description}</p>
        </div>
      {/if}

      {#if data.manwha.note}
        <div class="info-card">
          <h2 class="section-title">Personal Notes</h2>
          <p class="note-text">{data.manwha.note}</p>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  @reference "tailwindcss";

  .container {
    @apply max-w-6xl mx-auto px-4 py-6;
  }

  .header-section {
    @apply flex items-start justify-between mb-6 gap-4;
  }

  .page-title {
    @apply text-3xl font-bold text-gray-100 break-words;
  }

  .header-actions {
    @apply flex gap-2 flex-shrink-0;
  }

  .content-grid {
    @apply grid grid-cols-1 lg:grid-cols-[auto_1fr] gap-6;
  }

  .cover-section {
    @apply flex justify-center lg:justify-start;
  }

  .cover-button {
    @apply relative rounded-lg overflow-hidden border-2 border-gray-600
      shadow-lg transition-all focus:outline-none focus:ring-2
      focus:ring-purple-500;
    @apply max-w-xs w-full;
  }

  .cover-button.clickable {
    @apply cursor-pointer hover:border-purple-500 hover:shadow-purple-500/20;
  }

  .cover-button:not(.clickable) {
    @apply cursor-default;
  }

  .cover-image {
    @apply w-full h-auto object-cover;
    max-height: 600px;
  }

  .cover-overlay {
    @apply absolute inset-0 bg-black/70 flex flex-col items-center
      justify-center opacity-0 transition-opacity;
  }

  .cover-button:hover .cover-overlay {
    @apply opacity-100;
  }

  .overlay-icon {
    @apply text-white mb-2;
  }

  .overlay-text {
    @apply text-white text-lg font-semibold;
  }

  .info-section {
    @apply flex flex-col gap-6;
  }

  .info-card {
    @apply bg-gray-800 rounded-xl p-6 border border-gray-600 shadow-sm;
  }

  .section-title {
    @apply text-xl font-semibold mb-4 text-gray-100 pb-2 border-b
      border-gray-700;
  }

  .info-grid {
    @apply grid grid-cols-1 sm:grid-cols-2 gap-4;
  }

  .info-item {
    @apply flex flex-col gap-1;
  }

  .info-label {
    @apply text-sm font-medium text-gray-400;
  }

  .info-value {
    @apply text-base font-semibold text-gray-200;
  }

  .info-value.rating {
    @apply text-yellow-400;
  }

  .description-text {
    @apply text-gray-300 leading-relaxed whitespace-pre-wrap;
  }

  .note-text {
    @apply text-gray-300 leading-relaxed whitespace-pre-wrap bg-gray-900 p-4
      rounded-lg border border-gray-700;
  }
</style>
